# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 05:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('middle_initials', models.CharField(blank=True, help_text=b'Any initials, without space/comma', max_length=4, null=True)),
                ('make_bold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('event', models.TextField()),
                ('authors', models.ManyToManyField(to='bibliography.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.IntegerField()),
                ('journal', models.TextField()),
                ('volume', models.CharField(blank=True, max_length=8, null=True)),
                ('edition', models.CharField(blank=True, max_length=8, null=True)),
                ('page_start', models.CharField(blank=True, max_length=8, null=True)),
                ('page_end', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAuthorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('joint', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.Author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(through='bibliography.PublicationAuthorship', to='bibliography.Author'),
        ),
    ]
