# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(related_name='authors', through='bibliography.PublicationAuthorship', to='bibliography.Author'),
        ),
    ]
