# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightmove', '0004_propertyurl_outcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyurl',
            name='last_seen',
            field=models.DateTimeField(auto_created=True, help_text=b'Timestamp for previous discovery', null=True),
        ),
        migrations.AddField(
            model_name='propertyurl',
            name='postcode_outcode',
            field=models.CharField(blank=True, help_text=b'First part of the postcode', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='propertyurl',
            name='deactivated',
            field=models.DateTimeField(help_text=b'Timestamp for deactivation', null=True),
        ),
    ]
