# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightmove', '0006_auto_20170601_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyforsale',
            name='price_on_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertybase',
            name='agent_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='propertybase',
            name='agent_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='propertybase',
            name='agent_tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='n_bed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
