# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rightmove', '0009_auto_20170714_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyToRent',
            fields=[
                ('propertybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rightmove.PropertyBase')),
                ('payment_frequency', models.CharField(max_length=16)),
                ('is_retirement', models.BooleanField(default=False)),
                ('n_bed', models.IntegerField(blank=True, null=True)),
                ('asking_price', models.IntegerField()),
                ('price_on_application', models.BooleanField(default=False)),
                ('building_type', models.IntegerField(choices=[(0, b'Unknown type'), (1, b'Flat/apartment'), (2, b'Bungalow'), (3, b'Studio flat'), (4, b'Retirement property'), (5, b'Maisonette'), (6, b'Town house'), (7, b'House'), (8, b'Country house'), (9, b'Penthouse'), (10, b'Villa'), (11, b'Lodge'), (12, b'Chalet'), (13, b'Barn conversion'), (14, b'Cottage'), (15, b'Duplex'), (16, b'Mobile home'), (17, b'Park home')])),
                ('building_situation', models.IntegerField(blank=True, choices=[(1, b'Detached'), (2, b'Semi detached'), (3, b'End terrace'), (4, b'Mid terrace'), (5, b'Link detached'), (6, b'Flat'), (7, b'Ground floor')], null=True)),
                ('tenure_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            bases=('rightmove.propertybase',),
        ),
        migrations.AddField(
            model_name='propertybase',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
