# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightmove', '0010_auto_20171027_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytorent',
            name='tenure_type',
        ),
        migrations.AddField(
            model_name='propertytorent',
            name='inclusive_bills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertytorent',
            name='is_house_share',
            field=models.BooleanField(default=False),
        ),
    ]
