# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 02:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ListingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='NearestStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_mi', models.FloatField()),
                ('station', models.CharField(max_length=64)),
                ('national_rail', models.BooleanField(default=False)),
                ('tram', models.BooleanField(default=False)),
                ('underground', models.BooleanField(default=False)),
                ('overground', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed', models.DateTimeField(auto_created=True, help_text=b'Timestamp for access')),
                ('status_code', models.IntegerField()),
                ('full_description', models.TextField()),
                ('agent_name', models.CharField(max_length=256)),
                ('agent_address', models.CharField(max_length=256)),
                ('agent_tel', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PropertySitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed', models.DateTimeField(auto_created=True, help_text=b'Timestamp for access')),
                ('url', models.URLField(unique=True)),
                ('status_code', models.IntegerField()),
                ('last_modified', models.DateField(help_text=b'Last modified date according to the sitemap XML')),
                ('content', models.TextField()),
                ('urls_created', models.BooleanField(default=False, help_text=b'Have URLs been created/updated for this entry?')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deactivated', models.DateTimeField(auto_created=True, help_text=b'Timestamp for deactivation')),
                ('created', models.DateTimeField(auto_created=True, help_text=b'Timestamp for creation')),
                ('url', models.URLField(unique=True)),
                ('property_type', models.IntegerField(choices=[(1, b'residential property for sale'), (2, b'residential property to rent'), (3, b'residential new build property for sale'), (4, b'overseas property for sale'), (5, b'commercial property for sale'), (6, b'commercial property to rent')])),
                ('last_known_status', models.IntegerField(choices=[(1, b'active'), (2, b'removed'), (3, b'suspended'), (4, b'not found')])),
                ('last_accessed', models.DateTimeField(blank=True, help_text=b'Timestamp for previous access', null=True)),
                ('last_updated', models.DateTimeField(blank=True, help_text=b'Timestamp for previous update', null=True)),
                ('last_status_code', models.IntegerField(blank=True, help_text=b'Status code obtained on previous update', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyForSale',
            fields=[
                ('propertybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.PropertyBase')),
                ('n_bed', models.IntegerField()),
                ('asking_price', models.IntegerField()),
                ('building_type', models.IntegerField(choices=[(1, b'Detached'), (2, b'Semi detached'), (3, b'End terrace'), (4, b'Mid terrace'), (5, b'Flat'), (6, b'Bungalow')])),
            ],
            bases=('api.propertybase',),
        ),
        migrations.AddField(
            model_name='propertybase',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PropertyUrl'),
        ),
        migrations.AddField(
            model_name='neareststation',
            name='property_for_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PropertyBase'),
        ),
        migrations.AddField(
            model_name='listinghistory',
            name='property_for_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PropertyBase'),
        ),
        migrations.AddField(
            model_name='keyfeature',
            name='property_for_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PropertyBase'),
        ),
    ]
