# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForSaleSitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed', models.DateTimeField(auto_created=True, help_text=b'Timestamp for access')),
                ('url', models.URLField(unique=True)),
                ('status_code', models.IntegerField()),
                ('last_modified', models.DateField(help_text=b'Last modified date according to the sitemap XML')),
                ('content', models.TextField()),
            ],
        ),
    ]
