# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ListingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='NearestStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_mi', models.FloatField()),
                ('station', models.CharField(max_length=64)),
                ('national_rail', models.BooleanField(default=False)),
                ('tram', models.BooleanField(default=False)),
                ('underground', models.BooleanField(default=False)),
                ('overground', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed', models.DateTimeField(auto_created=True, help_text=b'Timestamp for access')),
                ('url', models.URLField()),
                ('status_code', models.IntegerField()),
                ('n_bed', models.IntegerField()),
                ('asking_price', models.IntegerField()),
                ('building_type', models.IntegerField(choices=[(1, b'Detached'), (2, b'Semi detached'), (3, b'End terrace'), (4, b'Mid terrace'), (5, b'Flat'), (6, b'Bungalow')])),
                ('key_features', models.TextField()),
                ('full_description', models.TextField()),
                ('agent_name', models.CharField(max_length=256)),
                ('agent_address', models.CharField(max_length=256)),
                ('agent_tel', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='neareststation',
            name='property_for_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PropertyForSale'),
        ),
        migrations.AddField(
            model_name='listinghistory',
            name='property_for_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PropertyForSale'),
        ),
        migrations.AddField(
            model_name='keyfeature',
            name='property_for_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PropertyForSale'),
        ),
    ]
