# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyfeature',
            name='property_for_sale',
        ),
        migrations.RemoveField(
            model_name='listinghistory',
            name='property_for_sale',
        ),
        migrations.AddField(
            model_name='propertybase',
            name='key_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertybase',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='KeyFeature',
        ),
        migrations.DeleteModel(
            name='ListingHistory',
        ),
    ]
