BUILDING_TYPE_DETACHED = 1
BUILDING_TYPE_SEMIDETACHED = 2
BUILDING_TYPE_ENDTERRACE = 3
BUILDING_TYPE_MIDTERRACE = 4
BUILDING_TYPE_FLAT = 5
BUILDING_TYPE_BUNGALOW = 6

BUILDING_TYPE_CHOICES = (
    (BUILDING_TYPE_DETACHED, "Detached"),
    (BUILDING_TYPE_SEMIDETACHED, "Semi detached"),
    (BUILDING_TYPE_ENDTERRACE, "End terrace"),
    (BUILDING_TYPE_MIDTERRACE, "Mid terrace"),
    (BUILDING_TYPE_FLAT, "Flat"),
    (BUILDING_TYPE_BUNGALOW, "Bungalow"),
)

