BUILDING_SITUATION_DETACHED = 1
BUILDING_SITUATION_SEMIDETACHED = 2
BUILDING_SITUATION_ENDTERRACE = 3
BUILDING_SITUATION_MIDTERRACE = 4
BUILDING_SITUATION_LINKDETACHED = 5
BUILDING_SITUATION_FLAT = 6
BUILDING_SITUATION_GROUNDFLOOR = 7

BUILDING_SITUATION_CHOICES = (
    (BUILDING_SITUATION_DETACHED, "Detached"),
    (BUILDING_SITUATION_SEMIDETACHED, "Semi detached"),
    (BUILDING_SITUATION_ENDTERRACE, "End terrace"),
    (BUILDING_SITUATION_MIDTERRACE, "Mid terrace"),
    (BUILDING_SITUATION_LINKDETACHED, "Link detached"),
    (BUILDING_SITUATION_FLAT, "Flat"),
    (BUILDING_SITUATION_GROUNDFLOOR, "Ground floor"),
)

BUILDING_TYPE_FLAT = 1
BUILDING_TYPE_BUNGALOW = 2
BUILDING_TYPE_STUDIO_FLAT = 3
BUILDING_TYPE_RETIREMENT = 4
BUILDING_TYPE_MAISONETTE = 5
BUILDING_TYPE_TOWNHOUSE = 6
BUILDING_TYPE_HOUSE = 7
BUILDING_TYPE_COUNTRYHOUSE = 8
BUILDING_TYPE_PENTHOUSE = 9

BUILDING_TYPE_CHOICES = (
    (BUILDING_TYPE_FLAT, "Flat/apartment"),
    (BUILDING_TYPE_BUNGALOW, "Bungalow"),
    (BUILDING_TYPE_STUDIO_FLAT, "Studio flat"),
    (BUILDING_TYPE_RETIREMENT, "Retirement property"),
    (BUILDING_TYPE_MAISONETTE, "Maisonette"),
    (BUILDING_TYPE_TOWNHOUSE, "Town house"),
    (BUILDING_TYPE_HOUSE, "House"),
    (BUILDING_TYPE_COUNTRYHOUSE, "Country house"),
    (BUILDING_TYPE_PENTHOUSE, "Penthouse"),
)

PROPERTY_TYPE_FORSALE = 1
PROPERTY_TYPE_TORENT = 2
PROPERTY_TYPE_NEWBUILD = 3
PROPERTY_TYPE_OVERSEAS = 4
PROPERTY_TYPE_COMMERCIALFORSALE = 5
PROPERTY_TYPE_COMMERCIALTORENT = 6

PROPERTY_TYPE_CHOICES = (
    (PROPERTY_TYPE_FORSALE, "residential property for sale"),
    (PROPERTY_TYPE_TORENT, "residential property to rent"),
    (PROPERTY_TYPE_NEWBUILD, "residential new build property for sale"),
    (PROPERTY_TYPE_OVERSEAS, "overseas property for sale"),
    (PROPERTY_TYPE_COMMERCIALFORSALE, "commercial property for sale"),
    (PROPERTY_TYPE_COMMERCIALTORENT, "commercial property to rent"),
)

PROPERTY_TYPE_MAP = {
    'property-for-sale': PROPERTY_TYPE_FORSALE,
    'property-to-rent': PROPERTY_TYPE_TORENT,
    'overseas-property': PROPERTY_TYPE_OVERSEAS,
    'new-homes-for-sale': PROPERTY_TYPE_NEWBUILD,
    'commercial-property-to-let': PROPERTY_TYPE_COMMERCIALTORENT,
    'commercial-property-for-sale': PROPERTY_TYPE_COMMERCIALFORSALE,
}

URL_STATUS_ACTIVE = 1
URL_STATUS_REMOVED = 2
URL_STATUS_SUSPENDED = 3
URL_STATUS_INACCESSIBLE = 4

URL_STATUS_CHOICES = (
    (URL_STATUS_ACTIVE, "active"),
    (URL_STATUS_REMOVED, "removed"),
    (URL_STATUS_SUSPENDED, "suspended"),
    (URL_STATUS_INACCESSIBLE, "not found"),
)