BUILDING_TYPE_DETACHED = 1
BUILDING_TYPE_SEMIDETACHED = 2
BUILDING_TYPE_ENDTERRACE = 3
BUILDING_TYPE_MIDTERRACE = 4
BUILDING_TYPE_FLAT = 5
BUILDING_TYPE_BUNGALOW = 6

BUILDING_TYPE_CHOICES = (
    (BUILDING_TYPE_DETACHED, "Detached"),
    (BUILDING_TYPE_SEMIDETACHED, "Semi detached"),
    (BUILDING_TYPE_ENDTERRACE, "End terrace"),
    (BUILDING_TYPE_MIDTERRACE, "Mid terrace"),
    (BUILDING_TYPE_FLAT, "Flat"),
    (BUILDING_TYPE_BUNGALOW, "Bungalow"),
)

PROPERTY_TYPE_FORSALE = 1
PROPERTY_TYPE_TORENT = 2
PROPERTY_TYPE_NEWBUILD = 3
PROPERTY_TYPE_OVERSEAS = 4
PROPERTY_TYPE_COMMERCIALFORSALE = 5
PROPERTY_TYPE_COMMERCIALTORENT = 6

PROPERTY_TYPE_CHOICES = (
    (PROPERTY_TYPE_FORSALE, "residential property for sale"),
    (PROPERTY_TYPE_TORENT, "residential property to rent"),
    (PROPERTY_TYPE_NEWBUILD, "residential new build property for sale"),
    (PROPERTY_TYPE_OVERSEAS, "overseas property for sale"),
    (PROPERTY_TYPE_COMMERCIALFORSALE, "commercial property for sale"),
    (PROPERTY_TYPE_COMMERCIALTORENT, "commercial property to rent"),
)

PROPERTY_TYPE_MAP = {
    'property-for-sale': PROPERTY_TYPE_FORSALE,
    'property-to-rent': PROPERTY_TYPE_TORENT,
    'overseas-property': PROPERTY_TYPE_OVERSEAS,
    'new-homes-for-sale': PROPERTY_TYPE_NEWBUILD,
    'commercial-property-to-let': PROPERTY_TYPE_COMMERCIALTORENT,
    'commercial-property-for-sale': PROPERTY_TYPE_COMMERCIALFORSALE,
}

URL_STATUS_ACTIVE = 1
URL_STATUS_REMOVED = 2
URL_STATUS_SUSPENDED = 3
URL_STATUS_INACCESSIBLE = 4

URL_STATUS_CHOICES = (
    (URL_STATUS_ACTIVE, "active"),
    (URL_STATUS_REMOVED, "removed"),
    (URL_STATUS_SUSPENDED, "suspended"),
    (URL_STATUS_INACCESSIBLE, "not found"),
)